on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  release:
    types:
      - released

jobs:
  static-build:
    runs-on: ubuntu-latest
    container: "alpine:latest"
    strategy:
      matrix:
        include:
          # cross toolchain downloads from: https://musl.cc/
          # you need to find the name ${cross_host}-cross.tgz
          # openssl_compiler choose from openssl source directory `./Configure LIST`
          - cross_host: arm-linux-musleabi
            openssl_compiler: linux-armv4
          - cross_host: aarch64-linux-musl
            openssl_compiler: linux-aarch64
          - cross_host: mips-linux-musl
            openssl_compiler: linux-mips32
          - cross_host: mipsel-linux-musl
            openssl_compiler: linux-mips32
          - cross_host: mips64-linux-musl
            openssl_compiler: linux64-mips64
          - cross_host: x86_64-linux-musl
            openssl_compiler: "linux-x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: compile
        env:
          CROSS_HOST: "${{ matrix.cross_host }}"
          OPENSSL_COMPILER: "${{ matrix.openssl_compiler }}"
        run: |
          if [ "${GITHUB_EVENT_NAME}" = release ]; then
            export ARIA2_VER="${GITHUB_REF##*/}"
          fi
          "${GITHUB_WORKSPACE}/build.sh"
      - name: zip archiving
        env:
          CROSS_HOST: "${{ matrix.cross_host }}"
        run: |
          apk add zip
          zip -j9v "/tmp/aria2-${CROSS_HOST}_static.zip" "${GITHUB_WORKSPACE}"/aria2c*
      - name: Prerelease Tag
        if: github.event_name == 'push' || github.event_name == 'schedule'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: /tmp/aria2-${{ matrix.cross_host }}_static.zip
          prerelease: true
          tag_name: continuous
          name: Continuous build
      - name: Upload Github Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/aria2-${{ matrix.cross_host }}_static.zip
          tag: ${{ github.ref }}
          overwrite: true
